language: python
python:
- 2.7
before_install:
- sudo apt-get install libcairomm-1.0-dev libboost-all-dev
- wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
- tar xf py2cairo-1.10.0.tar.bz2
- cd py2cairo-1.10.0
- ./waf configure --prefix=$(python -c "import sys; print(sys.prefix)")
- ./waf build
- ./waf install
- cd ..
- pip install sphinx coveralls
- ls /home/travis/virtualenv/python2.7/lib/pkgconfig
- export PKG_CONFIG_PATH=PKG_CONFIG_PATH:/home/travis/virtualenv/python2.7/lib/pkgconfig
install:
- python setup.py install
- cd
script:
- python -m DrawTurksHead
